server:
  port: 8091


spring:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

  datasource:
    username: postgres
    password: alesya
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  show-actuator: true
