server:
  port: 8090


spring:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

  datasource:
    username: postgres
    password: alesya
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres

  h2:
    console:
      enabled: true

