version: '2.1'
services:
  app:
    container_name: app_container
    build: .
    ports:
      - 8086:8080
      - 8087:8087
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/testdb"
      spring.datasource.username: "postgres"
      spring.datasource.password: "postgres"
    networks:
      - test_network

  db:
    container_name: db_container
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testdb"

    networks:
      - test_network

networks:
  test_network:


volumes:
  myvolume: